### ISSUE TITLE
Random Forest v2 order of classes

### ISSUE THREAD

**Issue by ignacioreyes** [alercebroker/ztf_explorer#105]
I think the right order for the classes (in a circle) might be something like:

- SNe
- DSCT
- EBC
- EBSDD
- RRL
- CEPH
- LPV
- Periodic Other
- AGN-I
- Blazar
- CV/Nova

@fforster @PaulaSanchezSaez @franzebauer  What do you think?

**Comment by dirodriguezm** [comment]
Closing this as classes have changed. Feel free to suggest a new order for the new taxonomy.
