### ISSUE TITLE
why do isdiffpos = f difference images show up as positive and not negative?

### ISSUE THREAD

**Issue by franzebauer** [alercebroker/ztf_explorer#149]
It would be much more intuitive if one were able to visually distinguish difference images where the science-template was positive or negative. Is this an issue with ZTF sending the diff-image as positive even when it is not? If so, perhaps we could invert it ourselves?

**Comment by fforster** [comment]
ZTF sends everything as positive, I think we shouldn't change that, but we should report that isdiffpos is negative.

**Comment by fforster** [comment]
Perhaps we can show the difference image times ifdiffpos (+1 or -1), which would only be inverted when the sign of isdiffpos is negative. If this is done at the API level then this also fixes the issues with the snhunter.

**Comment by franzebauer** [comment]
I would prefer to invert them so it is clear to the user that they are negative (multiplying by ifdiffpos +1 or -1 as say), or at least clearly label them on the image itself with a large F. And yes, this would ensure that we never send another isdiffpos = f alert again. ;)
