### ISSUE TITLE
provide full alert info for each difference image

### ISSUE THREAD

**Issue by franzebauer** [alercebroker/ztf_explorer#150]
a really critical missing element on the ZTF explorer is a link to the full ZTF alert info for each epoch/difference image that we provide.

**Comment by fforster** [comment]
Yes, this is in the todo list. We have an API to do that, so it should be easy to include (see https://alerceapi.readthedocs.io/en/latest/)

**Comment by cvalenzu** [comment]
added on 2dd6e36e3564f0e9de93a1474b5f2295697ee358
