### ISSUE TITLE
Hide light curve points with very large error bars

### ISSUE THREAD

**Issue by fforster** [alercebroker/ztf_explorer#152]
Given that ZTF provides difference fluxes we need to correct them with their reference flux, but sometimes the magnitude correction associated error can diverge. 

This happens when the denominator in the second term of this formula is close to zero (when the difference is negative and the reference and difference fluxes are similar):

![errors](https://user-images.githubusercontent.com/5090828/69487588-b94f6b00-0e00-11ea-8eda-fa2b98eadc24.png)

When this happens the error can become so large that it doesn't let one see the data clearly, e.g. https://alerce.online/object/ZTF17aaaowrw

![lc2](https://user-images.githubusercontent.com/5090828/69487654-e2243000-0e01-11ea-964c-96a3c36c7204.png)

but when you zoom in the large error dissapears:

![lc1](https://user-images.githubusercontent.com/5090828/69487699-5bbc1e00-0e02-11ea-8e76-336c304f428c.png)

I suggest that we should remove these points from the visualization when the errors are larger than a given value (1 mag?)

**Comment by cvalenzu** [comment]
Fixed on 59971cc
