### ISSUE TITLE
Warn that flux difference is negative when hovering

### ISSUE THREAD

**Issue by fforster** [alercebroker/ztf_explorer#153]
One could simply change the way the reference flux is shown, e.g. when you hover over a light curve point you see:
g: 16.345 +- 0.434,
but this could be shown as
g: (-) 16.345 +- 0.434,
if isdiffpos=-1

Also, in the associated image stamps one could change the Difference string for Diff. (negative), or simply plot the difference image times isdiffpos (as suggested by Franz).

**Comment by JavierArredondo** [comment]
In new version you can see isdiffpos in this format
![rsz_screenshot_from_2020-07-22_18-17-34](https://user-images.githubusercontent.com/19624900/88235340-abc8da00-cc48-11ea-8fc5-56597e158124.png)
