### ISSUE TITLE
issue with "no results found"

### ISSUE THREAD

**Issue by franzebauer** [alercebroker/ztf_explorer#159]
two issues:

1) when one first opens ztf explorer, it says no results found in the search panel. This is a bit confusing, since no search has been initiated.

2) when searching for all unclassified objects, no results are found, yet there are 9259 pages of no results? This is very confusing.

![image](https://user-images.githubusercontent.com/26261996/75669404-be228700-5c59-11ea-88cd-b8b7592d5f3d.png)

**Comment by dirodriguezm** [comment]
This issue is fixed for future release
