### ISSUE TITLE
bug: searching for individual sources, stamps from previous searched source appear initially for new source

### ISSUE THREAD

**Issue by franzebauer** [alercebroker/ztf_explorer#161]
I searched on ZTF19acryurj, clicked on the result to show the general info. Then I went back to the search tab and searched on ZTF19aculypc
The initial stamps shown for ZTF19aculypc are from ZTF19acryurj . When I click to change the stamps, the true stamps forZTF19aculypc appear. Something seems off in the memory or loading of the stamps.

**Comment by dirodriguezm** [comment]
Should be fixed in the newer version
