### ISSUE TITLE
Errors while loading explorer

### ISSUE THREAD

**Issue by fforster** [alercebroker/ztf_explorer#163]
I got the following warnings while loading a SN candidate in the explorer

![Screenshot from 2020-03-30 17-58-07](https://user-images.githubusercontent.com/5090828/77961673-92bea680-72b0-11ea-984e-a66f723ee126.png)

**Comment by fforster** [comment]
Offending object:
https://alerce.online/object/ZTF20aardftr

**Comment by dirodriguezm** [comment]
It seems to happen on every object. Not sure why yet. I'll take a look tomorrow.

**Comment by dirodriguezm** [comment]
Actually I think is more like a browser problem. Try opening it in a different one and check if its fixed.

**Comment by fforster** [comment]
I get similar errors in chrome

![Screenshot from 2020-03-30 19-25-39](https://user-images.githubusercontent.com/5090828/77967849-5bee8d80-72bc-11ea-8b67-1caed0688ca1.png)

**Comment by dirodriguezm** [comment]
These errors are related to the stamps API and will be handled differently for the future release.
