### ISSUE TITLE
Fit object view in 1080p screen without scrolling

### ISSUE THREAD

**Issue by ignacioreyes** [alercebroker/ztf_explorer#166]
Is it possible to shrink the components a little bit in the object view to make it fit in a 1080p screen without scrolling? I think it might improve the experience a little bit.

**Comment by dirodriguezm** [comment]
Yes I had the same idea, I can easily set the max size of the modal to be smaller but I just thought I would do it in the next version, when we remaster the explorer with the component library.

**Comment by dirodriguezm** [comment]
Some more adjustments needed
