### ISSUE TITLE
rerun stamp classifier on entire alert database

### ISSUE THREAD

**Issue by franzebauer** [alercebroker/ztf_explorer#168]
Not sure if this applies to light curve classifier, but the probabilities for the stamp classifier are not consistent throughout the database. Older alerts have probabilities up to 1.0 (with many just being flat out wrong such as ZTF19abqcowy), while newer ones saturate at ~0.7-0.8. 

While expensive, need to rerun the classifier on entire alert database every time a significant change is implemented in the classifier. Otherwise, it will be VERY confusing for users. This will be even more of a problem once the classifier and ALeRCE papers are in circulation, since it will prime users with certain expectations.

**Comment by cvalenzu** [comment]
This has been done with the new version of the stamp classifier
