### ISSUE TITLE
Period folding does not match in different bands

### ISSUE THREAD

**Issue by ignacioreyes** [alercebroker/ztf_explorer#170]
Look at https://alerce.online/object/ZTF18abfnktc when folded. For the first peak (phase between 0 and 1) both bands occur at the same time, but in the second phase (1-2) the red peak happens first.
![image](https://user-images.githubusercontent.com/13869886/85779517-ab90f980-b6f1-11ea-9645-6b1b9cf11544.png)

Are both light curves being folded with the same period?

**Comment by dirodriguezm** [comment]
The second part is just a concatenation of the first part. It is not calculated two times.

**Comment by dirodriguezm** [comment]
I see what you mean. This concatenation I mentioned should start at the point where the last band end.

**Comment by fforster** [comment]
The concatenation should start at a phase of 1.0, not where the points of the last band end. That's probably why this LC looks strange.

**Comment by dirodriguezm** [comment]
That was an easy fix. Will push the change to production now.
![image](https://user-images.githubusercontent.com/18015991/85783493-5f47b880-b6f5-11ea-8d3c-c806f1183a9b.png)
