### ISSUE TITLE
Light curve plot y-axis label is cropped for some screen resolutions

### ISSUE THREAD

**Issue by ale-munozarancibia** [alercebroker/ztf_explorer#174]
This screenshot corresponds to a maximized window, screen resolution 1366x768 (16:9) in Firefox (also happens in Chrome), Linux Fedora 29.
![Screenshot from 2020-07-17 20-27-35](https://user-images.githubusercontent.com/42121847/87840368-5a49d500-c86d-11ea-85ba-2c7ca947b556.png)

**Comment by JavierArredondo** [comment]
The label is now horizontally on top. For small screens it is not lost.
![image](https://user-images.githubusercontent.com/19624900/89228072-e9185a80-d5ac-11ea-9772-fb551084cdda.png)
