### ISSUE TITLE
Options shown at the bottom of the stamps panel overlap for some screen resolutions

### ISSUE THREAD

**Issue by ale-munozarancibia** [alercebroker/ztf_explorer#177]
The cross hairs option cannot be selected. This screenshot corresponds to a maximized window, screen resolution 1366x768 (16:9) in Firefox (also happens in Chrome), Linux Fedora 29.
![Screenshot from 2020-07-17 20-54-43](https://user-images.githubusercontent.com/42121847/87840860-cdece180-c86f-11ea-8692-0768540f6185.png)

**Comment by dirodriguezm** [comment]
Closed in #196
