### ISSUE TITLE
Detections missing in apparent and folded lightcurve

### ISSUE THREAD

**Issue by dirodriguezm** [alercebroker/ztf_explorer#230]

**Comment by cvalenzu** [comment]
Same as #229

**Comment by JavierArredondo** [comment]
In apparent light curve when I don't filter by corrected, this is the result for object [ZTF18abecbks:](http://dev.alerce.online/object/ZTF18abecbks). In detections not corrected the value is null.

![image](https://user-images.githubusercontent.com/19624900/89662902-bdde8580-d8a2-11ea-9464-556e04d9bfcb.png)

![image](https://user-images.githubusercontent.com/19624900/89663555-b4a1e880-d8a3-11ea-9368-ad22f0a93630.png)


My question is what fields I must to show?  for now we consider:
- Magnitudes
  - MJD
  - **magpsf_corr**
  - isdiffpos

magpsf_corr: I should show magpsf if corrected == false ???


- Errors bars
  - MJD
  - sigma psf: if detection was corrected we put sigmapsf_corr_ext, else should be sigmapsf. Issue #229 All 

This is the light curve only with corrected detections for the same object

![image](https://user-images.githubusercontent.com/19624900/89663450-90dea280-d8a3-11ea-96a4-eaf9663582a8.png)


Help please. @fforster @cvalenzu

**Comment by fforster** [comment]
Difference magnitude:
MJD, magpsf, sigmapsf
Apparent magnitude
MJD, magpsf_corr, sigmapsf_corr_ext
Folded
(MJD módulo period) / period, magpsf_corr, sigmapsf_corr_ext
