### ISSUE TITLE
Disable the search button for invalid queries

### ISSUE THREAD

**Issue by amoya87** [alercebroker/ztf_explorer#250]
Disable the search button for invalid queries:
Conesearch: incomplete params RA, DEC, Radius
Future discovery dates
Incomplete params probabily_class, probabily_class_name, probability

**Comment by cvalenzu** [comment]
The classifier, class and probability works without the full parameters, i.e. without class and probability it shows the classification done by the classifier for each object.

For conesearch we need to validate just ra,dec

Maybe not disabling the button just show an error and don't send the query to the api

**Comment by amoya87** [comment]
I was thinking about probability without classifier, and class !!!

**Comment by cvalenzu** [comment]
https://github.com/logaretm/vee-validate
https://vuetifyjs.com/en/components/forms/
https://github.com/vuelidate/vuelidate
