### ISSUE TITLE
Zoom, back and restore buttons of the light curves visor don't work

### ISSUE THREAD

**Issue by amoya87** [alercebroker/ztf_explorer#251]
![image](https://user-images.githubusercontent.com/17645028/89583408-4825db80-d808-11ea-9ed9-4a4bd6525081.png)

**Comment by cvalenzu** [comment]
They work for me, but the zoom "area" color is black, the constrast is too bad to see what is getting selected

**Comment by amoya87** [comment]
It works for me too. I didn't know how it worked.
