### ISSUE TITLE
The number of detection range min cannot be defined with value > 1000

### ISSUE THREAD

**Issue by amoya87** [alercebroker/ztf_explorer#255]
The number of detection range min cannot be defined with value > 1000

**Comment by cvalenzu** [comment]
Same as https://github.com/alercebroker/ztf_explorer/issues/215

**Comment by amoya87** [comment]
Validated at minimum, but at maximum there is a maximum threshold with control and not by typing.
![image](https://user-images.githubusercontent.com/17645028/89689262-ff3a5980-d8d1-11ea-9c1d-db60e3a197cb.png)
