### ISSUE TITLE
Objects with more than 1000 detections are not obtained

### ISSUE THREAD

**Issue by amoya87** [alercebroker/ztf_explorer#256]
oid = ZTF17aabvekq
![image](https://user-images.githubusercontent.com/17645028/89585888-a9e84480-d80c-11ea-97cf-1fb1695f60e1.png)

![image](https://user-images.githubusercontent.com/17645028/89586003-e6b43b80-d80c-11ea-9846-c97d5de14d9e.png)

**Comment by cvalenzu** [comment]
Same as https://github.com/alercebroker/ztf_explorer/issues/215

**Comment by amoya87** [comment]
Validado
