### ISSUE TITLE
Cannot move to a different page

### ISSUE THREAD

**Issue by fforster** [alercebroker/ztf_explorer#289]
When trying to select a different page in the left hiding menu, the pages option at the bottom left dissapears.
![Screenshot from 2020-08-26 09-37-50](https://user-images.githubusercontent.com/5090828/91310410-d8a86980-e77f-11ea-909d-c02a25dfff0a.png)

**Comment by dirodriguezm** [comment]
This happens when you hover in and out of the panel too quickly and the navigation buttons disappear when the panel is smaller but there is a problem with the events triggered by vuetify so the solution is not so easy unless we don't want to hide the navigation buttons.
