### ISSUE TITLE
bug: using explorer previous/next buttons fails to update stamps (initially)

### ISSUE THREAD

**Issue by franzebauer** [alercebroker/ztf_explorer#294]
Macbook Pro - Chrome browser version 85.0.4183.102 (Official Build) (64-bit)

open https://alerce.online/
search stamp, VS, P>0.7, MJD>59000
click on first result
use next button at upper right to go to next source
stamps and pulldown do not update.
=> highly reproducible up to this point.
clicking on the + magnifier will update the stamp and pulldown => after doing this once, stamps will update with next/previous button!
=> cannot reproduce this once I have clicked the + magnifier! (even after closing browser and reopening!)

**Comment by dirodriguezm** [comment]
I tried to reproduce but worked fine for me

**Comment by franzebauer** [comment]
same. could it have been a corrupted field in some cookie?

**Comment by dirodriguezm** [comment]
Clossing due to not reproducible or maybe just a one time situation.
