### ISSUE TITLE
List of oids in dev.alerce.online are displayed disorderly.

### ISSUE THREAD

**Issue by mperezcarrasco** [alercebroker/ztf_explorer#295]
When I search for some curves using a list of oids, the curves are displayed disorderly. That means that if I'm looking for the curves: ZTFoid4, ZTFoid3, ZTFoid2, ZTFoid1 (in that order) the explorer will return the curves in the order: ZTFoid1, ZTRoid2, ZTFoid3, ZTFoid4 (I'm not sure if this will be the real order because I used fake oids, but I think probably the explorer is returning alphabetically).

**Comment by dirodriguezm** [comment]
In the headers of the table you can see which column is sorted. By default its the Highest Probability.
![image](https://user-images.githubusercontent.com/18015991/92947845-e96b0780-f42e-11ea-8fd9-c88230899d61.png)

**Comment by cvalenzu** [comment]
I think the idea is to order in the same order as the list

**Comment by mperezcarrasco** [comment]
Right. In my case I want the order to be displayed in the same order as the entering list. Is it possible?
