### ISSUE TITLE
NED/SIMBAD/etc info is no longer reported in aladin window on mouseover

### ISSUE THREAD

**Issue by franzebauer** [alercebroker/ztf_explorer#309]
As of 1-2 months ago, I can no longer see NED info pop up when I click/mouse on the plus signs plotted in the aladin window of explorer.

I am using MacOS chrome Version 88.0.4324.150 (Official Build) (x86_64)

**Comment by dirodriguezm** [comment]
Hi, what browser were you using ? 

Is there a particular catalog data that should be displayed and it isn't ?

I just checked for some random object and get the table data on click

![image](https://user-images.githubusercontent.com/18015991/110154524-1dfac300-7dc3-11eb-947d-27e3a03e3eb1.png)

**Comment by franzebauer** [comment]
MacOS Chrome...Version 88.0.4324.150 (Official Build) (x86_64)

perhaps I need to delete a cookie or something?

**Comment by franzebauer** [comment]
I just deleted all alerce related cookies, did not help.

the problem is that I cannot see ANY catalog related data on click. nothing
shows up.

**Comment by dirodriguezm** [comment]
This should be fixed from the latest release.

**Comment by franzebauer** [comment]
Not fixed for me.
