### ISSUE TITLE
Improve size of EVENT and ACCESS_TIME labels

### ISSUE THREAD

**Issue by DiegoMellisG** [alercebroker/ztf_explorer#317]
In section "Discovery Date Filters" the calendar of Min and Max first greg date have ACCESS_TIME label out of margin. This label and EVENT label are bigger than the other fonts.

Image:

![out_of_margin](https://user-images.githubusercontent.com/26584639/112156559-1d389e00-8bc5-11eb-84d1-a8c4790b22b1.png)

**Comment by dirodriguezm** [comment]
This is a bug with the icon library. Should be fixed by correctly installing the icon pack or changing the icon label to a correct value
