### ISSUE TITLE
Link of a search isnt updated

### ISSUE THREAD

**Issue by JavierArredondo** [alercebroker/ztf_explorer#319]
When I find a list of objects with filters in dev, the url is updated with filters, but in prod this doesn't work...

On dev: https://dev.alerce.online/?oid=ZTF20aaelulu&oid=ZTF17aaafios&count=true&page=1&perPage=20&sortBy=probability&sortDesc=true 

On prod:  https://alerce.online/

**Comment by dirodriguezm** [comment]
I was going to work on solving this but when trying to reproduce it worked fine. Can you confirm @JavierArredondo ?

**Comment by JavierArredondo** [comment]
Now it works
