### ISSUE TITLE
Insufficient decimal places in period of folded light curves

### ISSUE THREAD

**Issue by JohnAstronomer** [alercebroker/ztf_explorer#339]
When the folder light curve of an object for example ZTF18abmstuw is displayed the period is shown to 3 decimal places ie 0.113 days. However this precision is insufficient to allow the light curve to be plotted in other software without recalculating the period. In the case of ZTF18abmstuw the period I (recalculated) is 0.112581765554218 days. This period produces a similar result to that shown on the ZTF Explorer page. I have not worked out how many decimal places / significant figures are required but it is greater than that shown. 

Attached file shows the phase plot using the period above in TOPCAT

![ZTF18abmstuw](https://user-images.githubusercontent.com/26068171/116616869-183ddb80-a935-11eb-8a0e-99b1b2b1c2c2.png)

**Comment by dirodriguezm** [comment]
Thanks for the suggestion, we are looking into it.
