### ISSUE TITLE
[BUG] multiple entries of same source when opening multiple-source alerce.online link

### ISSUE THREAD

**Issue by franzebauer** [alercebroker/ztf_explorer#350]
**Describe the bug**

when clicking on a link like this 
https://alerce.online/?oid=ZTF21acddrbu&oid=ZTF21acdezwk&oid=ZTF21acdksbr&oid=ZTF21accztoy&oid=ZTF21accyxid&oid=ZTF21accyvil&oid=ZTF21abtsoky&oid=ZTF21accrcuu&oid=ZTF21accohtt&count=true&page=1&perPage=1000&sortDesc=false

explorer will generate 6 entries for some sources
![image](https://user-images.githubusercontent.com/26261996/134214679-1786b68b-4cff-4736-96e3-b59594309f50.png)

**Expected behavior**
clearly ZTF21acdksbr should only be listed once. the presence of 6 entries screws up the arrow advancing feature across this source.

**Desktop (please complete the following information):**
 - Mac OS 11.5.1, chrome Version 93.0.4577.82 (Official Build) (x86_64)

**Comment by dirodriguezm** [comment]
That is kinda intended. You see one for each classifier, but now we added a feature where you can select a classifier so that it only appears once.
