### ISSUE TITLE
Include name resolver

### ISSUE THREAD

**Issue by pcastelln** [alercebroker/ztf_explorer#386]
Add a name resolver to the search form.

This should include a string field and a button, that fills in the coordinates for an object based on its common name. The search radius should be left unfilled and is responsibility of the user

- [x] Use [Sesame](http://cds.u-strasbg.fr/cgi-bin/Sesame) and parse the results for the coordinates
- [x] Include citation/acknowledgement/badge for Sesame
- [ ] Optional: Consider including a radiobutton to select between resolving with Simbad, NED and VizieR

**Comment by dirodriguezm** [comment]
Closed in https://github.com/alercebroker/ztf_explorer/pull/395 and https://github.com/alercebroker/component-library-old/pull/58
